### ISSUE TITLE
Reporte_Conexión de base de datos

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/conexion-de-bases-de-datos-equipo-xd#1]
[Reporte_Conexion de base datos.pdf](https://github.com/SistemasTecTlaxiaco/conexion-de-bases-de-datos-equipo-xd/files/6792180/Reporte_Conexion.de.base.datos.pdf)

**Comment by Yabin-2021** [comment]
Anexo Evaluación...

[Calificación de la práctica de Base de Datos.pdf](https://github.com/SistemasTecTlaxiaco/conexion-de-bases-de-datos-equipo-xd/files/6792590/Calificacion.de.la.practica.de.Base.de.Datos.pdf)

Calificación --- 20 de 20.

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
